services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adam-voice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ELEVENLABS_AGENT_ID=${ELEVENLABS_AGENT_ID}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - AGENT_ID=${AGENT_ID}
      - XI_API_KEY=${XI_API_KEY}
    env_file:
      - .env
    networks:
      - adam-network

networks:
  adam-network:
    driver: bridge